// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBl2eCiJScjKw6R6lDnXPluK7ltzAqzhr4',
    appId: '1:695015164113:web:ce222b3c307b8f7d4fddf0',
    messagingSenderId: '695015164113',
    projectId: 'chat-app-ca3ce',
    authDomain: 'chat-app-ca3ce.firebaseapp.com',
    storageBucket: 'chat-app-ca3ce.appspot.com',
    measurementId: 'G-FLCMTDGWY7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9ZAnOmu__PE8K8qr7yijM7u_xLPaVwus',
    appId: '1:695015164113:android:659a0def884aaff34fddf0',
    messagingSenderId: '695015164113',
    projectId: 'chat-app-ca3ce',
    storageBucket: 'chat-app-ca3ce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFHXQIqlORsuzGGavOAwUTjgg42Osgb-Y',
    appId: '1:695015164113:ios:ceb0c09862ad2a784fddf0',
    messagingSenderId: '695015164113',
    projectId: 'chat-app-ca3ce',
    storageBucket: 'chat-app-ca3ce.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );
}
